name: Deploy
on:
  push:
    branches:
      - master
env:
  SSH_KEY: some_key
jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Init ssh-key
        run: |
          cd 
          cd ..
          ls
          mkdir test
          ls
          echo aue_citati > test.txt
          cat ~/test/test.txt
