name: Deploy
on:
  push:
    branches:
      - master
env:
  SSH_KEY: some_key
jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create SSH key
        run: |
          mkdir -p ~/.ssh
          echo "HOST *" > ~/.ssh/config
          echo "StrictHostKeyChecking no" >> ~/.ssh/config
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_KEY }}" > ../private.key
          sudo chmod 600 ../private.key
          echo "${{ secrets.ALLOWED_HOSTS }}" > ~/.ssh/known_hosts
          echo "Somebullshitbruh" | ssh -oStrictHostKeyChecking=no admin@${{secrets.SERVER_IP}} "cat > /some_stupid_file.txt"
